#-------------------------------------------
# InvoiceShelf MySQL/MariaDB docker-compose variant
# Repo : https://github.com/InvoiceShelf/docker
#-------------------------------------------

services:
  database:
    container_name: invoiceshelf-mariadb
    image: mariadb:10
    environment:
      - MYSQL_DATABASE=invoiceshelf # ⚠️ Change DB name before proceeding
      - MYSQL_USER=invoiceshelf # ⚠️ Change DB username before proceeding
      - MYSQL_PASSWORD=somepass # ⚠️ Change DB password before proceeding
      - MYSQL_ROOT_PASSWORD=Ch@ng3_nn3 # 🚨 Change root password before proceeding
    volumes:
      - invoiceshelf_mariadb:/var/lib/mysql
    networks:
      - invoiceshelf
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  webapp:
    container_name: invoiceshelf-variant-mariadb
    image: invoiceshelf/invoiceshelf:nightly
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8090
      - DB_CONNECTION=mariadb
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=invoiceshelf # ⚠️ Change DB name before proceeding
      - DB_USERNAME=invoiceshelf # ⚠️ Change DB username before proceeding
      - DB_PASSWORD=somepass # ⚠️ Change DB password before proceeding
      - DB_PASSWORD_FILE=
      - SESSION_DOMAIN=localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:8090
    volumes:
      - invoiceshelf_storage:/var/www/html/storage/
      - invoiceshelf_modules:/var/www/html/Modules/
    ports:
      - "8090:8080" # 8090 is the public port.
    networks:
      - invoiceshelf
    restart: unless-stopped
    depends_on:
      - database

networks:
  invoiceshelf:

volumes:
  invoiceshelf_mariadb:
  invoiceshelf_storage:
  invoiceshelf_modules:
