#-------------------------------------------
# InvoiceShelf MySQL/MariaDB docker-compose variant
# Repo : https://github.com/InvoiceShelf/docker
#-------------------------------------------

services:
  database:
    container_name: invoiceshelf-mariadb
    image: mariadb:10
    environment:
      - MYSQL_DATABASE=invoiceshelf
      - MYSQL_USER=invoiceshelf
      - MYSQL_PASSWORD=somepass
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    volumes:
      - invoiceshelf_mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - invoiceshelf
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  webapp:
    container_name: invoiceshelf-variant-mariadb
    image: invoiceshelf/invoiceshelf:nightly
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8090
      - DB_CONNECTION=mariadb
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=invoiceshelf
      - DB_USERNAME=invoiceshelf
      - DB_PASSWORD=somepass
      - DB_PASSWORD_FILE=
      - SESSION_DOMAIN=localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:8090
    volumes:
      - invoiceshelf_storage:/var/www/html/storage/
    ports:
      - "8090:8080" # 8090 is the public port.
    networks:
      - invoiceshelf
    restart: unless-stopped
    depends_on:
      - database

networks:
  invoiceshelf:

volumes:
  invoiceshelf_mariadb:
  invoiceshelf_storage:
